export const mybooks = [
  {
    Accession_No: '1997001ROWH.002',
    AuthorIDs: 'AUT000000002',
    Author_Images: null,
    Author_Introductions: 'British author, best known for the Harry Potter series.',
    Authors: 'Rowling, J.K.',
    Book_ID: 'B00000000004',
    Book_Summary: 'First novel in the Harry Potter series.',
    Categories: 'Fantasy, Adventure',
    Cover_Image: null,
    ISBN_No: '9780747532743',
    ISSN_No: null,
    Language: 'English',
    No_of_Pages: 223,
    Publication_Year: '1997',
    PublisherID: 'PUB000000002',
    PublisherName: 'HarperCollins',
    SeriesID: 'SER000000002',
    SeriesName: 'A Song of Ice and Fire',
    Series_Description: 'Epic fantasy novels by George R. R. Martin.',
    Title: "Harry Potter and the Philosopher's Stone",
  },
  {
    Accession_No: '2011001MANT.001',
    AuthorIDs: 'AUT000000003',
    Author_Images: null,
    Author_Introductions: 'A famous author.',
    Authors: 'Martin, G.R.R.',
    Book_ID: 'B00000000005',
    Book_Summary: 'The first book in a series of fantasy novels.',
    Categories: 'Fantasy, Epic',
    Cover_Image: null,
    ISBN_No: '9780553103540',
    ISSN_No: null,
    Language: 'English',
    No_of_Pages: 694,
    Publication_Year: '2024',
    PublisherID: 'PUB000000003',
    PublisherName: 'Bantam Spectra',
    SeriesID: 'SER000000003',
    SeriesName: 'The Chronicles of Narnia',
    Series_Description: 'High fantasy novels by C.S. Lewis.',
    Title: 'A Game of Thrones',
  },
  {
    Accession_No: '1962001AAS.001',
    AuthorIDs: 'AUT000000004',
    Author_Images: null,
    Author_Introductions: 'An excellent author.',
    Authors: 'Lee, Harper',
    Book_ID: 'B00000000006',
    Book_Summary: 'A story of racial injustice in the American South.',
    Categories: 'Fiction, Drama',
    Cover_Image: null,
    ISBN_No: '9780061120084',
    ISSN_No: null,
    Language: 'English',
    No_of_Pages: 281,
    Publication_Year: '2023',
    PublisherID: 'PUB000000004',
    PublisherName: 'J. B. Lippincott & Co.',
    SeriesID: 'SER000000004',
    SeriesName: null,
    Series_Description: null,
    Title: 'To Kill a Mockingbird',
  },
  {
    Accession_No: '1954001AAS.002',
    AuthorIDs: 'AUT000000005',
    Author_Images: null,
    Author_Introductions: 'An amazing author.',
    Authors: 'Tolkien, J.R.R.',
    Book_ID: 'B00000000007',
    Book_Summary:
      'The Fellowship of the Ring is the first of three volumes in The Lord of the Rings.',
    Categories: 'Fantasy, Adventure',
    Cover_Image: null,
    ISBN_No: '9780618053267',
    ISSN_No: null,
    Language: 'English',
    No_of_Pages: 423,
    Publication_Year: '2022',
    PublisherID: 'PUB000000005',
    PublisherName: 'Houghton Mifflin Harcourt',
    SeriesID: 'SER000000005',
    SeriesName: null,
    Series_Description: null,
    Title: 'The Fellowship of the Ring',
  },
  {
    Accession_No: '2021001AAS.003',
    AuthorIDs: 'AUT000000006',
    Author_Images: null,
    Author_Introductions: 'A mysterious author.',
    Authors: 'Lark, Anya',
    Book_ID: 'B00000000008',
    Book_Summary: 'A book with suspense and fantasy.',
    Categories: 'Fantasy, Thriller',
    Cover_Image: null,
    ISBN_No: '9781234567890',
    ISSN_No: null,
    Language: 'English',
    No_of_Pages: 350,
    Publication_Year: '2024',
    PublisherID: 'PUB000000006',
    PublisherName: 'Lark Publishing',
    SeriesID: 'SER000000006',
    SeriesName: null,
    Series_Description: null,
    Title: 'The Shadow of the Whispering Woods',
  },
  {
    Accession_No: '2020001AAS.004',
    AuthorIDs: 'AUT000000007',
    Author_Images: null,
    Author_Introductions: 'An insightful author.',
    Authors: 'Chen, Li',
    Book_ID: 'B00000000009',
    Book_Summary: 'A book about the future of technology.',
    Categories: 'Science Fiction, Non-Fiction',
    Cover_Image: null,
    ISBN_No: '9781234567891',
    ISSN_No: null,
    Language: 'English',
    No_of_Pages: 400,
    Publication_Year: '2024',
    PublisherID: 'PUB000000007',
    PublisherName: 'Tech Innovations Inc.',
    SeriesID: 'SER000000007',
    SeriesName: null,
    Series_Description: null,
    Title: 'Future Echoes',
  },
  {
    Accession_No: '2023001AAS.005',
    AuthorIDs: 'AUT000000008',
    Author_Images: null,
    Author_Introductions: 'A talented author.',
    Authors: 'Duarte, Maria',
    Book_ID: 'B0000000010',
    Book_Summary: 'A passionate romance novel.',
    Categories: 'Romance, Fiction',
    Cover_Image: null,
    ISBN_No: '9781234567892',
    ISSN_No: null,
    Language: 'English',
    No_of_Pages: 300,
    Publication_Year: '2024',
    PublisherID: 'PUB000000008',
    PublisherName: 'Romance Reads',
    SeriesID: 'SER000000008',
    SeriesName: null,
    Series_Description: null,
    Title: 'The Whispering Heart',
  },
];
